name: GithubActionTest

on: [push]
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. pip 업그레이드
      run: python -m pip install --upgrade pip
    - name: 2. package install
      run: pip install requests
    - name: 3. python 실행
      run: python crawling.py
