name: GithubActionTest

on:
  schedule:
    - cron: '2 21 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests PyGithub==1.51 langchain==0.1.15 langchain_openai==0.1.2

    - name: Crawl webpage and save to file
      run: python crawling.py
      env: 
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
